var app = new Vue({
  el: '#table-container',
  data: {
    id: "thes",
    elements: [
      { atomicNumber: 1,   name: "Hydrogen",     abbreviation: "H",   id: "h",   period: "p-1",   group: "g-1",  block: "s",  atomicMass: 1.008,  boilingPoint: 20.271,  Meltingpoint: 13.99},
      { atomicNumber: 2,   name: "Helium",       abbreviation: "He",  id: "he",  period: "p-18",  group: "g-1" },
      { atomicNumber: 3,   name: "Lithium",      abbreviation: "Li",  id: "li",  period: "p-1",   group: "g-2" },
      { atomicNumber: 4,   name: "Beryllium",    abbreviation: "Be",  id: "be",  period: "p-2",   group: "g-2" },
      { atomicNumber: 5,   name: "Boron",        abbreviation: "B",   id: "b",   period: "p-13",  group: "g-2" },
      { atomicNumber: 6,   name: "Carbon",       abbreviation: "C",   id: "c",   period: "p-14",  group: "g-2" },
      { atomicNumber: 7,   name: "Nitrogen",     abbreviation: "N",   id: "n",   period: "p-15",  group: "g-2" },
      { atomicNumber: 8,   name: "Oxygen",       abbreviation: "O",   id: "o",   period: "p-16",  group: "g-2" },
      { atomicNumber: 9,   name: "Flourine",     abbreviation: "Fl",  id: "fl",  period: "p-17",  group: "g-2" },
      { atomicNumber: 10,  name: "Neon",         abbreviation: "N",   id: "n",   period: "p-18",  group: "g-2" },
      { atomicNumber: 11,  name: "Sodium",       abbreviation: "Na",  id: "na",  period: "p-1",   group: "g-3" },
      { atomicNumber: 12,  name: "Magnesium",    abbreviation: "Mg",  id: "mg",  period: "p-2",   group: "g-3" },
      { atomicNumber: 13,  name: "Aluminium",    abbreviation: "Al",  id: "al",  period: "p-13",  group: "g-3" },
      { atomicNumber: 14,  name: "Silicon",      abbreviation: "Si",  id: "si",  period: "p-14",  group: "g-3" },
      { atomicNumber: 15,  name: "Phosphorous",  abbreviation: "P",   id: "p",   period: "p-15",  group: "g-3" },
      { atomicNumber: 16,  name: "Sulfur",       abbreviation: "S",   id: "s",   period: "p-16",  group: "g-3" },
      { atomicNumber: 17,  name: "Chlorine",     abbreviation: "Cl",  id: "cl",  period: "p-17",  group: "g-3" },
      { atomicNumber: 18,  name: "Argon",        abbreviation: "Ar",  id: "ar",  period: "p-18",  group: "g-3" },
      { atomicNumber: 19,  name: "Potassium",    abbreviation: "K",   id: "k",   period: "p-1",   group: "g-4" },
      { atomicNumber: 20,  name: "Calcium",      abbreviation: "Ca",  id: "ca",  period: "p-2",   group: "g-4" },
      { atomicNumber: 21,  name: "Scandium",     abbreviation: "Sc",  id: "sc",  period: "p-3",   group: "g-4" },
      { atomicNumber: 22,  name: "Titanium",     abbreviation: "Ti",  id: "ti",  period: "p-4",   group: "g-4" },
      { atomicNumber: 23,  name: "Vanadium",     abbreviation: "V",   id: "v",   period: "p-5",   group: "g-4" },
      { atomicNumber: 24,  name: "Chromium",     abbreviation: "Cr",  id: "cr",  period: "p-6",   group: "g-4" },
      { atomicNumber: 25,  name: "Manganese",    abbreviation: "Mn",  id: "mn",  period: "p-7",   group: "g-4" },
      { atomicNumber: 26,  name: "Iron",         abbreviation: "Fe",  id: "fe",  period: "p-8",   group: "g-4" },
      { atomicNumber: 27,  name: "Cobalt",       abbreviation: "Co",  id: "co",  period: "p-9",   group: "g-4" },
      { atomicNumber: 28,  name: "Nickel",       abbreviation: "Ni",  id: "ni",  period: "p-10",  group: "g-4" },
      { atomicNumber: 29,  name: "Copper",       abbreviation: "Cu",  id: "cu",  period: "p-11",  group: "g-4" },
      { atomicNumber: 30,  name: "Zinc",         abbreviation: "Zn",  id: "zn",  period: "p-12",  group: "g-4" },
      { atomicNumber: 31,  name: "Gallium",      abbreviation: "Ga",  id: "ga",  period: "p-13",  group: "g-4" },
      { atomicNumber: 32,  name: "Germanium",    abbreviation: "Ge",  id: "ge",  period: "p-14",  group: "g-4" },
      { atomicNumber: 33,  name: "Arsenic",      abbreviation: "As",  id: "as",  period: "p-15",  group: "g-4" },
      { atomicNumber: 34,  name: "Selenium",     abbreviation: "Se",  id: "se",  period: "p-16",  group: "g-4" },
      { atomicNumber: 35,  name: "Bromine",      abbreviation: "Br",  id: "br",  period: "p-17",  group: "g-4" },
      { atomicNumber: 36,  name: "Krypton",      abbreviation: "Kr",  id: "kr",  period: "p-18",  group: "g-4" }
    ]
  }
})
