Vue.component("periodic-table", {
  template: "<p>I am a reusable component</p>"
})

var one = new Vue({
  el: '#grid-container',
  data: {
    elements: [
      { atomicNumber: 1,         name: "Hydrogen",      abbreviation: "H",       id: "h",   column: "c-2",   row: "r-2",   block: "s",  atomicMass: 1.008,    meltingPoint: 13.99,     boilingPoint: 20.271,    discoveryDate: 1766,            discoveredBy: "Henry Cavendish" },
      { atomicNumber: 2,         name: "Helium",        abbreviation: "He",      id: "he",  column: "c-36",  row: "r-2",   block: "s",  atomicMass: 4.003,    meltingPoint: -1,        boilingPoint: 4.222,     discoveryDate: 1895,            discoveredBy: "Sir William Ramsay, Per Teodor Cleve, and Nils Abraham" },
      { atomicNumber: 3,         name: "Lithium",       abbreviation: "Li",      id: "li",  column: "c-2",   row: "r-4",   block: "s",  atomicMass: 6.940,    meltingPoint: 453.65,    boilingPoint: 1615,      discoveryDate: 1817,            discoveredBy: "Johan August Arfvedson" },
      { atomicNumber: 4,         name: "Beryllium",     abbreviation: "Be",      id: "be",  column: "c-4",   row: "r-4",   block: "s",  atomicMass: 9.012,    meltingPoint: 1560,      boilingPoint: 2741,      discoveryDate: 1797,            discoveredBy: "Nicholas Louis Vauquelin" },
      { atomicNumber: 5,         name: "Boron",         abbreviation: "B",       id: "b",   column: "c-26",  row: "r-4",   block: "p",  atomicMass: 10.810,   meltingPoint: 2350,      boilingPoint: 4273,      discoveryDate: 1808,            discoveredBy: "Louis-Josef Gay-Lussac, Louis-Jacques Thénard, and Humphry Davy" },
      { atomicNumber: 6,         name: "Carbon",        abbreviation: "C",       id: "c",   column: "c-28",  row: "r-4",   block: "p",  atomicMass: 12.011,   meltingPoint: 4098,      boilingPoint: 4098,      discoveryDate: "Prehistoric",   discoveredBy: "Prehistoric" },
      { atomicNumber: 7,         name: "Nitrogen",      abbreviation: "N",       id: "n",   column: "c-30",  row: "r-4",   block: "p",  atomicMass: 14.007,   meltingPoint: 63.2,      boilingPoint: 77.355,    discoveryDate: 1772,            discoveredBy: "Daniel Rutherford" },
      { atomicNumber: 8,         name: "Oxygen",        abbreviation: "O",       id: "o",   column: "c-32",  row: "r-4",   block: "p",  atomicMass: 15.999,   meltingPoint: 54.36,     boilingPoint: 90.188,    discoveryDate: 1774,            discoveredBy: "Joseph Priestley and Carl Wilhelm Scheele" },
      { atomicNumber: 9,         name: "Flourine",      abbreviation: "F",       id: "f",   column: "c-34",  row: "r-4",    block: "p",  atomicMass: 18.998,   meltingPoint: 53.48,     boilingPoint: 85.04,     discoveryDate: 1886,            discoveredBy: "Henri Moissan" },
      { atomicNumber: 10,        name: "Neon",          abbreviation: "Ne",      id: "ne",  column: "c-36",  row: "r-4",   block: "p",  atomicMass: 20.180,   meltingPoint: 24.56,     boilingPoint: 27.104,    discoveryDate: 1898,            discoveredBy: "Sir William Ramsay and Morris Travers" },
      { atomicNumber: 11,        name: "Sodium",        abbreviation: "Na",      id: "na",  column: "c-2",   row: "r-6",   block: "s",  atomicMass: 22.990,   meltingPoint: 370.944,   boilingPoint: 1156.090,  discoveryDate: 1807,            discoveredBy: "Humphry Davy" },
      { atomicNumber: 12,        name: "Magnesium",     abbreviation: "Mg",      id: "mg",  column: "c-4",   row: "r-6",   block: "s",  atomicMass: 24.305,   meltingPoint: 923,       boilingPoint: 1363,      discoveryDate: 1755,            discoveredBy: "Joseph Black" },
      { atomicNumber: 13,        name: "Aluminium",     abbreviation: "Al",      id: "al",  column: "c-26",  row: "r-6",   block: "p",  atomicMass: 26.982,   meltingPoint: 933.473,   boilingPoint: 2792,      discoveryDate: 1825,            discoveredBy: "Hans Oersted" },
      { atomicNumber: 14,        name: "Silicon",       abbreviation: "Si",      id: "si",  column: "c-28",  row: "r-6",   block: "p",  atomicMass: 28.085,   meltingPoint: 1687,      boilingPoint: 3538,      discoveryDate: 1824,            discoveredBy: "Jöns Jacob Berzelius" },
      { atomicNumber: 15,        name: "Phosphorous",   abbreviation: "P",       id: "p",   column: "c-30",  row: "r-6",   block: "p",  atomicMass: 30.974,   meltingPoint: 317.3,     boilingPoint: 553.7,     discoveryDate: 1669,            discoveredBy: "Hennig Brandt" },
      { atomicNumber: 16,        name: "Sulfur",        abbreviation: "S",       id: "s",   column: "c-32",  row: "r-6",   block: "p",  atomicMass: 32.060,   meltingPoint: 388.36,    boilingPoint: 717.76,    discoveryDate: "Prehistoric",   discoveredBy: "Prehistoric" },
      { atomicNumber: 17,        name: "Chlorine",      abbreviation: "Cl",      id: "cl",  column: "c-34",  row: "r-6",   block: "p",  atomicMass: 35.450,   meltingPoint: 171.7,     boilingPoint: 239.11,    discoveryDate: 1774,            discoveredBy: "Carl Wilhelm Scheele" },
      { atomicNumber: 18,        name: "Argon",         abbreviation: "Ar",      id: "ar",  column: "c-36",  row: "r-6",   block: "p",  atomicMass: 39.948,   meltingPoint: 83.81,     boilingPoint: 87.302,    discoveryDate: 1894,            discoveredBy: "Lord Rayleigh and Sir William Ramsay" },
      { atomicNumber: 19,        name: "Potassium",     abbreviation: "K",       id: "k",   column: "c-2",   row: "r-8",   block: "s",  atomicMass: 39.098,   meltingPoint: 336.7,     boilingPoint: 1032,      discoveryDate: 1807,            discoveredBy: "Humphry Davy" },
      { atomicNumber: 20,        name: "Calcium",       abbreviation: "Ca",      id: "ca",  column: "c-4",   row: "r-8",   block: "s",  atomicMass: 40.078,   meltingPoint: 1115,      boilingPoint: 1757,      discoveryDate: 1808,            discoveredBy: "Humphry Davy" },
      { atomicNumber: 21,        name: "Scandium",      abbreviation: "Sc",      id: "sc",  column: "c-6",   row: "r-8",   block: "d",  atomicMass: 44.956,   meltingPoint: 1814,      boilingPoint: 3109,      discoveryDate: 1879,            discoveredBy: "Lars Frederik Nilson" },
      { atomicNumber: 22,        name: "Titanium",      abbreviation: "Ti",      id: "ti",  column: "c-8",   row: "r-8",   block: "d",  atomicMass: 47.867,   meltingPoint: 1943,      boilingPoint: 3560,      discoveryDate: 1791,            discoveredBy: "William Gregor" },
      { atomicNumber: 23,        name: "Vanadium",      abbreviation: "V",       id: "v",   column: "c-10",  row: "r-8",   block: "d",  atomicMass: 50.942,   meltingPoint: 2183,      boilingPoint: 3680,      discoveryDate: 1801,            discoveredBy: "Andrés Manuel del Río" },
      { atomicNumber: 24,        name: "Chromium",      abbreviation: "Cr",      id: "cr",  column: "c-12",  row: "r-8",   block: "d",  atomicMass: 51.996,   meltingPoint: 2180,      boilingPoint: 2944,      discoveryDate: 1798,            discoveredBy: "Nicholas Louis Vauquelin" },
      { atomicNumber: 25,        name: "Manganese",     abbreviation: "Mn",      id: "mn",  column: "c-14",  row: "r-8",   block: "d",  atomicMass: 54.938,   meltingPoint: 1519,      boilingPoint: 2334,      discoveryDate: 1774,            discoveredBy: "Johan Gottlieb Gahn" },
      { atomicNumber: 26,        name: "Iron",          abbreviation: "Fe",      id: "fe",  column: "c-16",  row: "r-8",   block: "d",  atomicMass: 55.845,   meltingPoint: 1811,      boilingPoint: 3134,      discoveryDate: "~ 3500 B.C.",   discoveredBy: "N / A" },
      { atomicNumber: 27,        name: "Cobalt",        abbreviation: "Co",      id: "co",  column: "c-18",  row: "r-8",   block: "d",  atomicMass: 58.933,   meltingPoint: 1768,      boilingPoint: 3200,      discoveryDate: 1739,            discoveredBy: "Georg Brandt" },
      { atomicNumber: 28,        name: "Nickel",        abbreviation: "Ni",      id: "ni",  column: "c-20",  row: "r-8",   block: "d",  atomicMass: 58.693,   meltingPoint: 1728,      boilingPoint: 3186,      discoveryDate: 1751,            discoveredBy: "Axel Fredrik Cronstedt" },
      { atomicNumber: 29,        name: "Copper",        abbreviation: "Cu",      id: "cu",  column: "c-22",  row: "r-8",   block: "d",  atomicMass: 63.546,   meltingPoint: 1357.77,   boilingPoint: 2833,      discoveryDate: "Prehistoric",   discoveredBy: "Prehistoric" },
      { atomicNumber: 30,        name: "Zinc",          abbreviation: "Zn",      id: "zn",  column: "c-24",  row: "r-8",   block: "d",  atomicMass: 65.380,   meltingPoint: 692.677,   boilingPoint: 1180,      discoveryDate: 1746,            discoveredBy: "Andreas Marggraf" },  //discoveryDate as "Zinc" was 1746, but Greeks and Romans knew about element before -20
      { atomicNumber: 31,        name: "Gallium",       abbreviation: "Ga",      id: "ga",  column: "c-26",  row: "r-8",   block: "p",  atomicMass: 69.723,   meltingPoint: 302.9146,  boilingPoint: 2502,      discoveryDate: 1875,            discoveredBy: "Paul-Émile Lecoq de Boisbaudran" },
      { atomicNumber: 32,        name: "Germanium",     abbreviation: "Ge",      id: "ge",  column: "c-28",  row: "r-8",   block: "p",  atomicMass: 72.630,   meltingPoint: 1211.4,    boilingPoint: 3106,      discoveryDate: 1886,            discoveredBy: "Clemens Winkler" },
      { atomicNumber: 33,        name: "Arsenic",       abbreviation: "As",      id: "as",  column: "c-30",  row: "r-8",   block: "p",  atomicMass: 74.922,   meltingPoint: 889,       boilingPoint: 889,       discoveryDate: "~1250",         discoveredBy: "Albertus Magnus" },
      { atomicNumber: 34,        name: "Selenium",      abbreviation: "Se",      id: "se",  column: "c-32",  row: "r-8",   block: "p",  atomicMass: 78.971,   meltingPoint: 494,       boilingPoint: 958,       discoveryDate: 1817,            discoveredBy: "Jöns Jacob Berzelius" },
      { atomicNumber: 35,        name: "Bromine",       abbreviation: "Br",      id: "br",  column: "c-34",  row: "r-8",   block: "p",  atomicMass: 79.904,   meltingPoint: 266,       boilingPoint: 322,       discoveryDate: 1826,            discoveredBy: "Antoine-Jérôme Balard and Carl Löwig" },
      { atomicNumber: 36,        name: "Krypton",       abbreviation: "Kr",      id: "kr",  column: "c-36",  row: "r-8",   block: "p",  atomicMass: 83.798,   meltingPoint: 115.78,    boilingPoint: 119.735,   discoveryDate: 1898,            discoveredBy: "Sir William Ramsay and Morris Travers" },
      { atomicNumber: 37,        name: "Rubidium",      abbreviation: "Rb",      id: "rb",  column: "c-2",   row: "r-10",  block: "s",  atomicMass: 85.468,   meltingPoint: 312.45,    boilingPoint: 961,      discoveryDate: 1861,            discoveredBy: "Gustav Kirchhoff and Robert Bunsen" },
      { atomicNumber: 38,        name: "Strontium",     abbreviation: "Sr",      id: "sr",  column: "c-4",   row: "r-10",  block: "s",  atomicMass: 87.620,   meltingPoint: 1050,      boilingPoint: 1650,     discoveryDate: 1790,            discoveredBy: "Adair Crawford" },
      { atomicNumber: 39,        name: "Yttrium",       abbreviation: "Y",       id: "y",   column: "c-6",   row: "r-10",  block: "d",  atomicMass: 88.906,   meltingPoint: 1795,      boilingPoint: 3618,     discoveryDate: 1794,            discoveredBy: "Johan Gadolin" },
      { atomicNumber: 40,        name: "Zirconium",     abbreviation: "Zr",      id: "zr",  column: "c-8",   row: "r-10",  block: "d",  atomicMass: 91.224,   meltingPoint: 2127,      boilingPoint: 4679,     discoveryDate: 1789,            discoveredBy: "Martin Heinrich Klaproth"},
      { atomicNumber: 41,        name: "Niobium",       abbreviation: "Nb",      id: "nb",  column: "c-10",  row: "r-10",  block: "d",  atomicMass: 92.906,   meltingPoint: 2750,      boilingPoint: 5014,     discoveryDate: 1801,            discoveredBy: "Charles Hatchett" },
      { atomicNumber: 42,        name: "Molybdenum",    abbreviation: "Mo",      id: "mo",  column: "c-12",  row: "r-10",  block: "d",  atomicMass: 95.950,   meltingPoint: 2895,      boilingPoint: 4912,     discoveryDate: 1781,            discoveredBy: "Peter Jacob Hjelm" },
      { atomicNumber: 43,        name: "Technetium",    abbreviation: "Tc",      id: "tc",  column: "c-14",  row: "r-10",  block: "d",  atomicMass: "(98)",   meltingPoint: 2430,      boilingPoint: 4535,     discoveryDate: 1937,            discoveredBy: "Carlo Perrier and Emilio Segre`" },
      { atomicNumber: 44,        name: "Ruthenium",     abbreviation: "Ru",      id: "ru",  column: "c-16",  row: "r-10",  block: "d",  atomicMass: 101.07,   meltingPoint: 2606,      boilingPoint: 4420,     discoveryDate: 1844,            discoveredBy: "Karl Karlovich Klaus" },
      { atomicNumber: 45,        name: "Rhodium",       abbreviation: "Rh",      id: "rh",  column: "c-18",  row: "r-10",  block: "d",  atomicMass: 102.906,  meltingPoint: 2236,      boilingPoint: 3968,     discoveryDate: 1803,            discoveredBy: "William Hyde Wollaston" },
      { atomicNumber: 46,        name: "Palladium",     abbreviation: "Pd",      id: "pd",  column: "c-20",  row: "r-10",  block: "d",  atomicMass: 106.42,   meltingPoint: 1828,      boilingPoint: 3236,     discoveryDate: 1803,            discoveredBy: "William Hyde Wollastom" },
      { atomicNumber: 47,        name: "Silver",        abbreviation: "Ag",      id: "ag",  column: "c-22",  row: "r-10",  block: "d",  atomicMass: 107.868,  meltingPoint: 1234.93,   boilingPoint: 2435,     discoveryDate: "~ 3000 B.C.",   discoveredBy: "N/A"},
      { atomicNumber: 48,        name: "Cadmium",       abbreviation: "Cd",      id: "cd",  column: "c-24",  row: "r-10",  block: "d",  atomicMass: 112.414,  meltingPoint: 594.219,   boilingPoint: 1040,     discoveryDate: 1817,            discoveredBy: "Friedrich Stromeyer" },
      { atomicNumber: 49,        name: "Indium",        abbreviation: "In",      id: "in",  column: "c-26",  row: "r-10",  block: "p",  atomicMass: 114.818,  meltingPoint: 429.75,    boilingPoint: 2300,     discoveryDate: 1863,            discoveredBy: "Ferdinand Reich and Hieronymous Richter" },
      { atomicNumber: 50,        name: "Tin",           abbreviation: "Sn",      id: "sn",  column: "c-28",  row: "r-10",  block: "p",  atomicMass: 118.710,  meltingPoint: 505.078,   boilingPoint: 2859,     discoveryDate: "~ 2100 B.C.",   discoveredBy: "N / A" },
      { atomicNumber: 51,        name: "Antmony",       abbreviation: "Sb",      id: "sb",  column: "c-30",  row: "r-10",  block: "p",  atomicMass: 121.760,  meltingPoint: 903.778,   boilingPoint: 1860,     discoveryDate: "~ 1600 B.C.",   discoveredBy: "N / A" },
      { atomicNumber: 52,        name: "Tellurium",     abbreviation: "Te",      id: "te",  column: "c-32",  row: "r-10",  block: "p",  atomicMass: 127.60,   meltingPoint: 722.66,    boilingPoint: 1261,     discoveryDate: 1783,            discoveredBy: "Franz-Joseph Müler von Reichenstein" },
      { atomicNumber: 53,        name: "Iodine",        abbreviation: "I",       id: "i",   column: "c-34",  row: "r-10",  block: "p",  atomicMass: 126.904,  meltingPoint: 386.9,     boilingPoint: 457.6,    discoveryDate: 1811,            discoveredBy: "Bernard Courtois" },
      { atomicNumber: 54,        name: "Xenon",         abbreviation: "Xe",      id: "xe",  column: "c-36",  row: "r-10",  block: "p",  atomicMass: 131.293,  meltingPoint: 161.4,     boilingPoint: 165.051,  discoveryDate: 1898,            discoveredBy: "Sir William Ramsay and Morris Travers" },
      { atomicNumber: 55,        name: "Caesium",       abbreviation: "Cs",      id: "cs",  column: "c-2",   row: "r-12",  block: "s",  atomicMass: 132.905,  meltingPoint: 301.7,     boilingPoint: 944,      discoveryDate: 1860,            discoveredBy: "Gustav Kirchhoff and Robert Bunsen" },
      { atomicNumber: 56,        name: "Barium",        abbreviation: "Ba",      id: "ba",  column: "c-4",   row: "r-12",  block: "s",  atomicMass: 137.327,  meltingPoint: 1000,      boilingPoint: 2118,     discoveryDate: 1808,            discoveredBy: "Humphry Davy" },

      // Extended portion of periodic table.
      { atomicNumber: 57,        name: "Lanthanum",     abbreviation: "La",      id: "la",  column: "c-6",   row: "r-17",  block: "f",  atomicMass: 138.905,  meltingPoint: 1193,      boilingPoint: 3737,      discoveryDate: 1839,           discoveredBy: "Carl Gustav Mosander" },
      { atomicNumber: 58,        name: "Cerium",        abbreviation: "Ce",      id: "ce",  column: "c-8",   row: "r-17",  block: "f",  atomicMass: 140.116,  meltingPoint: 1072,      boilingPoint: 3716,      discoveryDate: 1803,           discoveredBy: "Jo..ns Jacob Berzelius and Wilhelm Hisinger" },
      { atomicNumber: 59,        name: "Praseodymium",  abbreviation: "Pr",      id: "pr",  column: "c-10",  row: "r-17",  block: "f",  atomicMass: 140.908,  meltingPoint: 1204,      boilingPoint: 3793,      discoveryDate: 1885,           discoveredBy: "Carl Auer von Welsbach" },
      { atomicNumber: 60,        name: "Neodymium",     abbreviation: "Nd",      id: "nd",  column: "c-12",  row: "r-17",  block: "f",  atomicMass: 144.242,  meltingPoint: 1289,      boilingPoint: 3347,      discoveryDate: 1885,           discoveredBy: "Carl Auer von Welsbach" },
      { atomicNumber: 61,        name: "Promethium",    abbreviation: "Pm",      id: "pm",  column: "c-14",  row: "r-17",  block: "f",  atomicMass: "(145)",  meltingPoint: 1315,      boilingPoint: 3273,      discoveryDate: 1945,           discoveredBy: "Jacob A. Marinsky, Lawrence E. Glendenin, and Charles D. Coryell" },
      { atomicNumber: 62,        name: "Samarium",      abbreviation: "Sm",      id: "sm",  column: "c-16",  row: "r-17",  block: "f",  atomicMass: 150.36,   meltingPoint: 1345,      boilingPoint: 2067,      discoveryDate: 1879,           discoveredBy: "Paul-E`mile Lecoq de Boisbaudran" },
      { atomicNumber: 63,        name: "Europium",      abbreviation: "Eu",      id: "eu",  column: "c-18",  row: "r-17",  block: "f",  atomicMass: 151.964,  meltingPoint: 1095,      boilingPoint: 1802,      discoveryDate: 1901,           discoveredBy: "Euge'ne-Anatole Demarc'ay" },
      { atomicNumber: 64,        name: "Gadolinium",    abbreviation: "Gd",      id: "gd",  column: "c-20",  row: "r-17",  block: "f",  atomicMass: 157.25,   meltingPoint: 1586,      boilingPoint: 3546,      discoveryDate: 1880,           discoveredBy: "Jean Charles Galissard de Marignac"},
      { atomicNumber: 65,        name: "Terbium",       abbreviation: "Tb",      id: "tb",  column: "c-22",  row: "r-17",  block: "f",  atomicMass: 158.925,  meltingPoint: 1632,      boilingPoint: 3503,      discoveryDate: 1843,           discoveredBy: "Carl Gustav Mosander" },
      { atomicNumber: 66,        name: "Dysprosium",    abbreviation: "Dy",      id: "dy",  column: "c-24",  row: "r-17",  block: "f",  atomicMass: 162.500,  meltingPoint: 1685,      boilingPoint: 2840,      discoveryDate: 1886,           discoveredBy: "Paul-Émile Lecoq de Boisbaudran" },


      { atomicNumber: 72,        name: "Hafnium",       abbreviation: "Hf",      id: "hf",  column: "c-8",   row: "r-12",  block: "d",  atomicMass: 178.49,   meltingPoint: 2506,      boilingPoint: 4873,      discoveryDate: 1923,           discoveredBy: "George Charles de Hevesy and Dirk Coster" },
      { atomicNumber: 73,        name: "Tantalum",      abbreviation: "Ta",      id: "ta",  column: "c-10",  row: "r-12",  block: "d",  atomicMass: 180.948,  meltingPoint: 3290,      boilingPoint: 5728,      discoveryDate: 1802,           discoveredBy: "Anders Gustav Ekeberg" },
      { atomicNumber: 74,        name: "Tungsten",      abbreviation: "W",       id: "w",   column: "c-12",  row: "r-12",  block: "d",  atomicMass: 183.84,   meltingPoint: 3687,      boilingPoint: 5828,      discoveryDate: 1783,           discoveredBy: "Juan Elhuyar and Fausto Elhuyar" },
      { atomicNumber: 75,        name: "Rhenium",       abbreviation: "Re",      id: "re",  column: "c-14",  row: "r-12",  block: "d",  atomicMass: 186.207,  meltingPoint: 3458,      boilingPoint: 5863,      discoveryDate: 1925,           discoveredBy: "Walter Noddack, Ida Tacke, and Otto Berg" },
      { atomicNumber: 76,        name: "Osmium",        abbreviation: "Os",      id: "os",  column: "c-16",  row: "r-12",  block: "d",  atomicMass: 190.23,   meltingPoint: 3306,      boilingPoint: 5281,      discoveryDate: 1803,           discoveredBy: "Smithson Tennant" },
      { atomicNumber: 77,        name: "Iridium",       abbreviation: "Ir",      id: "ir",  column: "c-18",  row: "r-12",  block: "d",  atomicMass: 192.217,  meltingPoint: 2719,      boilingPoint: 4701,      discoveryDate: 1803,           discoveredBy: "Smithson Tennant" },
      { atomicNumber: 78,        name: "Platinum",      abbreviation: "Pt",      id: "pt",  column: "c-20",  row: "r-12",  block: "d",  atomicMass: 195.084,  meltingPoint: 2041.4,    boilingPoint: 4098,      discoveryDate: "Unknown",      discoveredBy: "South Americans before Colombus" },
      { atomicNumber: 79,        name: "Gold",          abbreviation: "Au",      id: "au",  column: "c-22",  row: "r-12",  block: "d",  atomicMass: 196.967,  meltingPoint: 1337.33,   boilingPoint: 3109,      discoveryDate: "~ 3000 B.C.",  discoveredBy: "N / A"},
      { atomicNumber: 80,        name: "Mercury",       abbreviation: "Hg",      id: "hg",  column: "c-24",  row: "r-12",  block: "d",  atomicMass: 200.592,  meltingPoint: 234.321,   boilingPoint: 629.769,   discoveryDate: "~ 1500 B.C.",  discoveredBy: "N / A" },
      { atomicNumber: 81,        name: "Thallium",      abbreviation: "Tl",      id: "tl",  column: "c-26",  row: "r-12",  block: "p",  atomicMass: 204.38,   meltingPoint: 577,       boilingPoint: 1746,      discoveryDate: 1861,           discoveredBy: "William Crookes" },
      { atomicNumber: 82,        name: "Lead",          abbreviation: "Pb",      id: "pb",  column: "c-28",  row: "r-12",  block: "p",  atomicMass: 207.2,    meltingPoint: 600.612,   boilingPoint: 2022,      discoveryDate: "Ancient",      discoveredBy: "N / A"},

      { atomicNumber: 87,        name: "Francium",      abbreviation: "Fr",      id: "fr",  column: "c-2",   row: "r-14",  block: "s",  atomicMass: "(223)",  meltingPoint: 294,       boilingPoint: 923,       discoveryDate: 1939,           discoveredBy: "Marguerite Perey" },
      { atomicNumber: 88,        name: "Radium",        abbreviation: "Ra",      id: "ra",  column: "c-4",   row: "r-14",  block: "s",  atomicMass: "(226)",  meltingPoint: 969,       boilingPoint: 1773,      discoveryDate: 1898,           discoveredBy: "Pierre Curie and Marie Curie" },
      { atomicNumber: 118,       name: "Oganesson",     abbreviation: "Og",      id: "og",  column: "c-36",  row: "r-14",  block: "p"},

      // Currently, the atomicNumber must be exactly the same as the index in the array (this helps get the object that the user hovers over)
      { atomicNumber: 119,      name: "Lanthanides",    abbreviation: "Lan.",    id: "z1",  column: "c-6",   row: "r-12",  block: "f",  atomicMass: "1",       meltingPoint: "",        boilingPoint: "",        discoveryDate: "2",             discoveredBy: "3" },
      { atomicNumber: 120,      name: "Actinides",      abbreviation: "Act.",    id: "z2",  column: "c-6",   row: "r-14",  block: "f",  atomicMass: "1",       meltingPoint: "",        boilingPoint: "",        discoveryDate: "2",             discoveredBy: "3" },
    ],
    rowLabels: [
      // Row labels
      { display: 1,   column: "cc-1",   row: "rr-2" },
      { display: 2,   column: "cc-1",   row: "rr-4" },
      { display: 3,   column: "cc-1",   row: "rr-6" },
      { display: 4,   column: "cc-1",   row: "rr-8" },
      { display: 5,   column: "cc-1",   row: "rr-10" },
      { display: 6,   column: "cc-1",   row: "rr-12" },
      { display: 7,   column: "cc-1",   row: "rr-14" }
    ],
    colLabels: [
      // Column labels
      { display: " 1",   column: "cc-2",   row: "rr-1" },
      { display: " 2",   column: "cc-4",   row: "rr-1" },
      { display: " 3",   column: "cc-6",   row: "rr-1" },
      { display: " 4",   column: "cc-8",   row: "rr-1" },
      { display: " 5",   column: "cc-10",  row: "rr-1" },
      { display: " 6",   column: "cc-12",  row: "rr-1" },
      { display: " 7",   column: "cc-14",  row: "rr-1" },
      { display: " 8",   column: "cc-16",  row: "rr-1" },
      { display: " 9",   column: "cc-18",  row: "rr-1" },
      { display: "10",   column: "cc-20",  row: "rr-1" },
      { display: "11",   column: "cc-22",  row: "rr-1" },
      { display: "12",   column: "cc-24",  row: "rr-1" },
      { display: "13",   column: "cc-26",  row: "rr-1" },
      { display: "14",   column: "cc-28",  row: "rr-1" },
      { display: "15",   column: "cc-30",  row: "rr-1" },
      { display: "16",   column: "cc-32",  row: "rr-1" },
      { display: "17",   column: "cc-34",  row: "rr-1" },
      { display: "18",   column: "cc-36",  row: "rr-1" }
    ],
    // These elements are the defaults. Should only change when  user clicks on a different tab like "orbitals", "properties", etc.
    elementsDefaultColor: [
      "blue",
      "blue",
      "blue",
      "blue",
      "red",
      "red",
      "red",
      "red",
      "red",
      "red",
      "blue",
      "blue",
      "red",
      "red",
      "red",
      "red",
      "red",
      "red",
      "blue",
      "blue",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "red",
      "red",
      "red",
      "red",
      "red",
      "red",
      "blue",
      "blue",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "red",
      "red",
      "red",
      "red",
      "red",
      "red", //54 Xenon
      "blue",
      "blue",
      "orange",
      "orange",
      "orange",
      "orange",
      "orange",
      "orange",
      "orange",
      "orange",
      "orange",
      "orange",

      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "red",
      "red",
      "red",
      "red",
      "red",
      "red",

      "blue",
      "blue",
      "red",

      "orange",
      "orange"
  ],
  // These colors should be displayed
  elementColors: [
      "blue",
      "blue",
      "blue",
      "blue",
      "red",
      "red",
      "red",
      "red",
      "red",
      "red",
      "blue",
      "blue",
      "red",
      "red",
      "red",
      "red",
      "red",
      "red",
      "blue",
      "blue",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "red",
      "red",
      "red",
      "red",
      "red",
      "red",
      "blue",
      "blue",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "red",
      "red",
      "red",
      "red",
      "red",
      "red", //54 Xenon
      "blue",
      "blue",
      "orange",
      "orange",
      "orange",
      "orange",
      "orange",
      "orange",
      "orange",
      "orange",
      "orange",
      "orange",

      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "green",
      "red",
      "red",
      "red",
      "red",
      "red",
      "red",

      "blue",
      "blue",
      "red",

      "orange",
      "orange"
    ],
    hoverAtomicNumber: "1",
    hoverAbbreviation: "H",
    hoverName: "Hydrogen",
    hoverAtomicMass: 1.008,
    hoverBlock: "s",
    hoverColor: "blue", //This actually changes the color

    hoverDiscoveryDate: "1766",
    hoverDiscoveredBy: "Henry Cavendish"
  },
  methods: {
    updateElementInfoAndDesc: function(index) {
      // Update element overview
      this.hoverAtomicNumber = this.$refs.elementIndexDOM[index].innerHTML;
      this.hoverAbbreviation = this.$refs.elementAbbreviationDOM[index].innerHTML;
      this.hoverName = this.$refs.elementNameDOM[index].innerHTML;
      this.hoverAtomicMass = this.$refs.elementAtomicMassDOM[index].innerHTML;

      // Update element description
      this.hoverDiscoveryDate = this.elements[index].discoveryDate;
      this.hoverDiscoveredBy = this.elements[index].discoveredBy;
      this.hoverColor = this.elementsDefaultColor[index];
    },

    shadeElementOnHover: function(index) {
      // Gets the default color of the hovered over element
      var defaultColor = this.elementColors[index];

      // If the element is in its default state, prefix "dark-" to it. (There is a dark-blue, dark-red etc. CSS property for all colors)
      if(defaultColor == "blue" || defaultColor == "green" || defaultColor == "red" || defaultColor == "orange") {
        Vue.set(this.elementColors, index, ("dark-" + this.elementColors[index]));
      }
    },

    lightenElementOnHover: function(index) {
        // Saves the default color of the element to the hovered over element
        Vue.set(this.elementColors, index, (this.elementsDefaultColor[index]));
    },

    highlightRowCol: function(index, rowOrCol) {
      console.log(index + 1);
    }
  },
  computed: {

  }
})
